### PR TITLE
Revert "Fixes #56 (Bug in %U)"

### LINKED ISSUE #56: Possible bug with %U
This looks like a bug with %U:

console.log( strftime('%U', (new Date('03-25-2017 00:00:00'))) )  // 12
console.log( strftime('%U', (new Date('03-26-2017 00:00:00'))) )  // 13
console.log( strftime('%U', (new Date('03-27-2017 00:00:00'))) )  // 12
console.log( strftime('%U', (new Date('04-02-2017 00:00:00'))) )  // 13

### PR DESCRIPTION
**Pull request by samsonjs**
Sorry, premature merge ... the tests fail.

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
I guess the reason is in UTC tests and timezone difference. We have to do something with that :worried:

File: strftime.js [hunk 1]
```diff
@@ -595,10 +595,8 @@
             else
                 weekday--;
         }
-
-        var firstDayOfYearUtc = Date.UTC(date.getFullYear(), 0, 1),
-            dateUtc = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()),
-            yday = Math.floor((dateUtc - firstDayOfYearUtc) / 86400000),
+        var firstDayOfYear = new Date(date.getFullYear(), 0, 1),
```
Comment (samsonjs) [inline strftime.js]: Do we need to add the tz offset from `date` to `firstDayOfYearUtc`? This might be a bug. In some timezones the bug wouldn't manifest, but in others it will.

**Comment by samsonjs** [comment]
In C I get "12" for %U for time 1307472705 from the tests whether I use `gmtime` or `localtime`. Should the week number should be the same in any timezone, since we should compare to 1-Jan in the date's timezone?

File: strftime.js (hunk 1 above)
Comment (alexandrnikitin) [inline strftime.js]: The intention was to compare date without taking DST into account. `date.getDate()` returns proper day with DST. But the difference calculated without DST. 

Could you point when the bug could appear here please. I'm not sure I get you.

**Comment by alexandrnikitin** [comment]
I don't follow you. The date from the tests `Time = new Date(1307472705067); // Tue, 07 Jun 2011 18:51:45 GMT` shows "23" for %U for me.
The week number should be the same in any timezone. Just comparison made in UTC to avoid DST.

**Comment by samsonjs** [comment]
Yeah, it looks right to me. I can't find anything wrong with the function. I'm going to try and nail down why the test is failing for me.

**Comment by alexandrnikitin** [comment]
Could you post more details about the failing test please.

**Comment by samsonjs** [comment]
I get this error.

```
[ 1:37pm] ~/Projects/strftime:master % make test
TZ=America/Vancouver node test.js
[ OK ] Deprecated exports
[ OK ] Exports
[ OK ] Time zones (America/Vancouver)

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: strftime.utc()("%U", Sun Mar 26 2017 00:00:00 GMT-0700 (PDT)) is "13", expected "12"
    at assertFormat (/Users/sjs/Projects/strftime/test.js:21:12)
    at Function.assert.format (/Users/sjs/Projects/strftime/test.js:27:5)
    at Object.<anonymous> (/Users/sjs/Projects/strftime/test.js:118:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
make: *** [test] Error 8
```

I think the problem is that the dates in the tests should be constant no matter which timezone they are run in. Submitted PR #60 that I think addresses this correctly. Let me know what you think.
